name: 'GitHub Actions Weather Bot'

on:
  schedule:
    - cron: '* * * * 1'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'curl'
        run: bash ./curl.sh
