name: 'curl'

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
#       - name: 'Get Weather'
#         run: bash ./weather.sh
#       - name: 'Get Date'
#         run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
#       - name: 'Send mail'
#         uses: dawidd6/action-send-mail@master
#         with: 
#           server_address: smtp.163.com
#           server_port: 465
#           username: ${{ secrets.MAIL_USERNAME }}
#           password: ${{ secrets.MAIL_PASSWORD }}
#           subject: Shanghai Weather Report (${{env.REPORT_DATE}})
#           body: file://result.html
#           to: yifeng.ruan@gmail.com
#           from: GitHub Actions
#           content_type: text/html
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools requests beautifulsoup4 lxml
      - name: 'sendDingding'
        run: python BaiduIndex.py
