name: 'WeatherBot'

on:
  schedule:
    - cron: '0 0,10 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools requests
      - name: 'sendDingding'
        run: python Weather.py
